Repository NREL/SAM, pull requests merged in 2021-12, with the labels that each got.

#830 hide labels and parametric on dispatch choice ui, to match non-standalone options
  deploy/runtime/ui/Battery Dispatch Standalone Options BTM.txt
  deploy/runtime/ui/Battery Dispatch Standalone Options FOM.txt
Labels: bug, battery

#842 move critical load equations after load scaling
  deploy/runtime/ui/Electric Load Crit.txt
Labels: bug

#844 update sales tax percent to be the same for all techs
  deploy/runtime/defaults/Biopower_Merchant Plant.txt
  deploy/runtime/defaults/Biopower_Single Owner.txt
  deploy/runtime/defaults/Generic Battery_Commercial.txt
  deploy/runtime/defaults/Generic Battery_Host Developer.txt
  deploy/runtime/defaults/Generic Battery_Residential.txt
  deploy/runtime/defaults/Generic System_Host Developer.txt
  deploy/runtime/defaults/PV Battery_Commercial.txt
  deploy/runtime/defaults/PV Battery_Host Developer.txt
  deploy/runtime/defaults/PV Battery_Residential.txt
  deploy/runtime/defaults/PVWatts Battery_Commercial.txt
  deploy/runtime/defaults/PVWatts Battery_Host Developer.txt
  deploy/runtime/defaults/PVWatts Battery_Residential.txt
  deploy/runtime/defaults/Standalone Battery_Commercial.txt
  deploy/runtime/defaults/Standalone Battery_Host Developer.txt
  deploy/runtime/defaults/Standalone Battery_Residential.txt
  deploy/runtime/defaults/Wind Power_Commercial.txt
  deploy/runtime/defaults/Wind Power_Residential.txt
  test_results_win64.csv
Labels: bug

#845 GitHub actions for Linux on sam
  .github/workflows/ci.yml
Labels: enhancement

#855 Batt dispatch choice variables matching default page loads
  deploy/runtime/defaults/Fuel Cell_Single Owner.txt
  deploy/runtime/defaults/Generic Battery_All Equity Partnership Flip.txt
  deploy/runtime/defaults/Generic Battery_Leveraged Partnership Flip.txt
  deploy/runtime/defaults/Generic Battery_Merchant Plant.txt
  deploy/runtime/defaults/Generic Battery_Sale Leaseback.txt
  deploy/runtime/defaults/PV Battery_Merchant Plant.txt
  deploy/runtime/defaults/Standalone Battery_All Equity Partnership Flip.txt
  deploy/runtime/defaults/Standalone Battery_Leveraged Partnership Flip.txt
  deploy/runtime/defaults/Standalone Battery_Merchant Plant.txt
  deploy/runtime/defaults/Standalone Battery_Sale Leaseback.txt
  deploy/runtime/defaults/Standalone Battery_Single Owner.txt
  test_results_win64.csv
Labels: bug

#859 Update README.md
  README.md
Labels: enhancement

#858 ensure all monthly grid power targets have default value length 12
  deploy/runtime/defaults/PV Battery_Commercial.txt
  deploy/runtime/defaults/Standalone Battery_Host Developer.txt
  deploy/runtime/defaults/Standalone Battery_Residential.txt
  deploy/runtime/defaults/Standalone Battery_Third Party.txt
Labels: bug
