Repository NREL/SAM, pull requests merged in 2021-11, with the labels that each got.

#720 Fix battery sizing behavior when switching between kWh and h definitions
  deploy/runtime/defaults/Fuel Cell_Commercial.txt
  deploy/runtime/defaults/Fuel Cell_Single Owner.txt
  deploy/runtime/defaults/Generic Battery_All Equity Partnership Flip.txt
  deploy/runtime/defaults/Generic Battery_Commercial.txt
  deploy/runtime/defaults/Generic Battery_Host Developer.txt
  deploy/runtime/defaults/Generic Battery_Leveraged Partnership Flip.txt
  deploy/runtime/defaults/Generic Battery_Merchant Plant.txt
  deploy/runtime/defaults/Generic Battery_Residential.txt
  deploy/runtime/defaults/Generic Battery_Sale Leaseback.txt
  deploy/runtime/defaults/Generic Battery_Single Owner.txt
  deploy/runtime/defaults/Generic Battery_Third Party.txt
  deploy/runtime/defaults/PV Battery_All Equity Partnership Flip.txt
  deploy/runtime/defaults/PV Battery_Commercial.txt
  deploy/runtime/defaults/PV Battery_Host Developer.txt
  deploy/runtime/defaults/PV Battery_Leveraged Partnership Flip.txt
  deploy/runtime/defaults/PV Battery_Merchant Plant.txt
  deploy/runtime/defaults/PV Battery_Residential.txt
  deploy/runtime/defaults/PV Battery_Sale Leaseback.txt
  deploy/runtime/defaults/PV Battery_Single Owner.txt
  deploy/runtime/defaults/PV Battery_Third Party.txt
  deploy/runtime/ui/Battery Bank Sizing.txt
Labels: battery

#729 Pvwattsv8
  deploy/runtime/defaults/Fuel Cell_Commercial.txt
  deploy/runtime/defaults/Fuel Cell_Single Owner.txt
  deploy/runtime/defaults/PVWatts Battery_Commercial.txt
  deploy/runtime/defaults/PVWatts Battery_Host Developer.txt
  deploy/runtime/defaults/PVWatts Battery_Residential.txt
  deploy/runtime/defaults/PVWatts Battery_Third Party.txt
  deploy/runtime/defaults/PVWatts_All Equity Partnership Flip.txt
  deploy/runtime/defaults/PVWatts_Commercial.txt
  deploy/runtime/defaults/PVWatts_Host Developer.txt
  deploy/runtime/defaults/PVWatts_LCOE Calculator.txt
  deploy/runtime/defaults/PVWatts_Leveraged Partnership Flip.txt
  deploy/runtime/defaults/PVWatts_Merchant Plant.txt
  deploy/runtime/defaults/PVWatts_None.txt
  deploy/runtime/defaults/PVWatts_Residential.txt
  deploy/runtime/defaults/PVWatts_Sale Leaseback.txt
  deploy/runtime/defaults/PVWatts_Single Owner.txt
  deploy/runtime/defaults/PVWatts_Third Party.txt
  deploy/runtime/startup.lk
  deploy/runtime/ui/PVWatts Advanced Inputs.txt
  deploy/runtime/ui/PVWatts Land Area.txt
  deploy/runtime/ui/PVWatts.txt
Labels: enhancement, new feature, pv

#725 Wave Resource API calls
  deploy/runtime/defaults/MEtidal_LCOE Calculator.txt
  deploy/runtime/defaults/MEwave_LCOE Calculator.txt
  deploy/runtime/defaults/MEwave_None.txt
  deploy/runtime/ui/Marine Array.txt
  deploy/runtime/ui/Marine Costs - O&M.txt
  deploy/runtime/ui/Marine Wave Resource Time Series.txt
  deploy/runtime/ui/Wind Resource File.txt
  deploy/runtime/webapis.conf
  deploy/wave_resource_ts/CalWave_California_Wave-Resource.csv
  deploy/wave_resource_ts/Humboldt_California_Wave-Resource.csv
  deploy/wave_resource_ts/Jannettes-Pier_North-Carolina_Wave-Resource.csv
  deploy/wave_resource_ts/PacWave-North_Oregon_Wave-Resource.csv
  deploy/wave_resource_ts/PacWave-South_Oregon_Wave-Resource.csv
  deploy/wave_resource_ts/USACE_North-Carolina_Wave-Resource.csv
  deploy/wave_resource_ts/WETS_Hawaii_Wave-Resource.csv
  deploy/wave_resource_ts/lat21.47_lon-157.75__2010.csv
  deploy/wave_resource_ts/lat34.52_lon-120.69__2010.csv
  deploy/wave_resource_ts/lat35.91_lon-75.59__2010.csv
  deploy/wave_resource_ts/lat36.19_lon-75.75__2010.csv
  deploy/wave_resource_ts/lat40.84_lon-124.25__2010.csv
  deploy/wave_resource_ts/lat44.57_lon-124.23__2010.csv
  deploy/wave_resource_ts/lat44.69_lon-124.14__2010.csv
  src/invoke.cpp
  src/library.cpp
  src/wavetoolkit.cpp
  src/wavetoolkit.h
Labels: weather

#758 Add unsupported rate units error message
  src/invoke.cpp
  src/urdb.cpp
  src/urdb.h
Labels: enhancement, utility rate

#742 Sloped Terrain inputs for Single Axis trackers
  deploy/runtime/defaults/Flat Plate PV_All Equity Partnership Flip.txt
  deploy/runtime/defaults/Flat Plate PV_Commercial.txt
  deploy/runtime/defaults/Flat Plate PV_Host Developer.txt
  deploy/runtime/defaults/Flat Plate PV_LCOE Calculator.txt
  deploy/runtime/defaults/Flat Plate PV_Leveraged Partnership Flip.txt
  deploy/runtime/defaults/Flat Plate PV_Merchant Plant.txt
  deploy/runtime/defaults/Flat Plate PV_None.txt
  deploy/runtime/defaults/Flat Plate PV_Residential.txt
  deploy/runtime/defaults/Flat Plate PV_Sale Leaseback.txt
  deploy/runtime/defaults/Flat Plate PV_Single Owner.txt
  deploy/runtime/defaults/Flat Plate PV_Third Party.txt
  deploy/runtime/defaults/PV Battery_All Equity Partnership Flip.txt
  deploy/runtime/defaults/PV Battery_Commercial.txt
  deploy/runtime/defaults/PV Battery_Host Developer.txt
  deploy/runtime/defaults/PV Battery_Leveraged Partnership Flip.txt
  deploy/runtime/defaults/PV Battery_Merchant Plant.txt
  deploy/runtime/defaults/PV Battery_Residential.txt
  deploy/runtime/defaults/PV Battery_Sale Leaseback.txt
  deploy/runtime/defaults/PV Battery_Single Owner.txt
  deploy/runtime/defaults/PV Battery_Third Party.txt
  deploy/runtime/ui/PV System Design.txt
Labels: new feature, pv

#756 Update pvsamv1 to apply DC degradation linearly
  deploy/runtime/ui/Degradation DC Lifetime.txt
  deploy/runtime/versions.lk
  test_results_win64.csv
Labels: pv

#757 Fix bug in billing demand yr 0 peaks
  deploy/runtime/ui/Utility Rate - Billing Demand.txt
Labels: bug, utility rate

#781 Update batt_bank_size_ui in version upgrade script
  deploy/runtime/versions.lk
Labels: bug, battery

#789 add alternative battery surface area calculatons
  deploy/runtime/defaults/Generic Battery_All Equity Partnership Flip.txt
  deploy/runtime/defaults/Generic Battery_Commercial.txt
  deploy/runtime/defaults/Generic Battery_Host Developer.txt
  deploy/runtime/defaults/Generic Battery_Leveraged Partnership Flip.txt
  deploy/runtime/defaults/Generic Battery_Merchant Plant.txt
  deploy/runtime/defaults/Generic Battery_Residential.txt
  deploy/runtime/defaults/Generic Battery_Sale Leaseback.txt
  deploy/runtime/defaults/Generic Battery_Single Owner.txt
  deploy/runtime/defaults/Generic Battery_Third Party.txt
  deploy/runtime/defaults/PV Battery_All Equity Partnership Flip.txt
  deploy/runtime/defaults/PV Battery_Commercial.txt
  deploy/runtime/defaults/PV Battery_Host Developer.txt
  deploy/runtime/defaults/PV Battery_Leveraged Partnership Flip.txt
  deploy/runtime/defaults/PV Battery_Merchant Plant.txt
  deploy/runtime/defaults/PV Battery_Residential.txt
  deploy/runtime/defaults/PV Battery_Sale Leaseback.txt
  deploy/runtime/defaults/PV Battery_Single Owner.txt
  deploy/runtime/defaults/PV Battery_Third Party.txt
  deploy/runtime/defaults/PVWatts Battery_Commercial.txt
  deploy/runtime/defaults/PVWatts Battery_Host Developer.txt
  deploy/runtime/defaults/PVWatts Battery_Residential.txt
  deploy/runtime/defaults/PVWatts Battery_Third Party.txt
  deploy/runtime/defaults/Standalone Battery_All Equity Partnership Flip.txt
  deploy/runtime/defaults/Standalone Battery_Commercial.txt
  deploy/runtime/defaults/Standalone Battery_Host Developer.txt
  deploy/runtime/defaults/Standalone Battery_Leveraged Partnership Flip.txt
  deploy/runtime/defaults/Standalone Battery_Merchant Plant.txt
  deploy/runtime/defaults/Standalone Battery_Residential.txt
  deploy/runtime/defaults/Standalone Battery_Sale Leaseback.txt
  deploy/runtime/defaults/Standalone Battery_Single Owner.txt
  deploy/runtime/defaults/Standalone Battery_Third Party.txt
  deploy/runtime/ui/Battery Replacements.txt
  deploy/runtime/ui/Battery Thermal.txt
  src/defmgr.cpp
Labels: enhancement, battery

#813 Set pointers to nullptr in header files
  src/defmgr.cpp
  src/results.h
  src/stochastic.h
Labels: bug

#819 add labels to battery dispatch variables where missing
  deploy/runtime/ui/Battery Dispatch Common.txt
  deploy/runtime/ui/Battery Dispatch Options BTM.txt
  deploy/runtime/ui/Battery Dispatch Peak Shaving BTM.txt
  deploy/runtime/ui/Battery Dispatch Standalone Options BTM.txt
  deploy/runtime/ui/Battery Dispatch Standalone Options FOM.txt
  deploy/runtime/ui/Fuel Cell Dispatch Manual.txt
Labels: bug
