Repository NREL/SAM, pull requests merged in 2022-02, with the labels that each got.

#907 Split testing into two steps for readability
  .github/workflows/ci.yml
Labels: enhancement

#863 Default diff notebook
  test/Run defaults diff.ipynb
  test/run_defaults_diff.py
Labels: enhancement

#897 Update Wind Turbine Characteristics equation behavior
  deploy/runtime/ui/Wind Turbine Design.txt
Labels: bug, wind

#892 Make JPD file from downloaded time series wave resource data
  deploy/runtime/defaults/MEtidal_LCOE Calculator.txt
  deploy/runtime/defaults/MEtidal_None.txt
  deploy/runtime/defaults/MEwave_LCOE Calculator.txt
  deploy/runtime/defaults/MEwave_None.txt
  deploy/runtime/startup.lk
  deploy/runtime/ui/Marine Array.txt
  deploy/runtime/ui/Marine Wave Resource Header.txt
  deploy/runtime/ui/Marine Wave Resource Time Series.txt
  deploy/runtime/ui/Marine Wave Resource.txt
  deploy/runtime/ui/Solar Resource Data.txt
  src/invoke.cpp
  src/library.cpp
  src/wavetoolkit.cpp
  src/wavetoolkit.h
Labels: new feature, requires help revision

#928 Updated land area calculations for PV and PVWatts
  deploy/runtime/defaults/Flat Plate PV_All Equity Partnership Flip.txt
  deploy/runtime/defaults/Flat Plate PV_Commercial.txt
  deploy/runtime/defaults/Flat Plate PV_Host Developer.txt
  deploy/runtime/defaults/Flat Plate PV_LCOE Calculator.txt
  deploy/runtime/defaults/Flat Plate PV_Leveraged Partnership Flip.txt
  deploy/runtime/defaults/Flat Plate PV_Merchant Plant.txt
  deploy/runtime/defaults/Flat Plate PV_None.txt
  deploy/runtime/defaults/Flat Plate PV_Residential.txt
  deploy/runtime/defaults/Flat Plate PV_Sale Leaseback.txt
  deploy/runtime/defaults/Flat Plate PV_Single Owner.txt
  deploy/runtime/defaults/Flat Plate PV_Third Party.txt
  deploy/runtime/defaults/Fuel Cell_Commercial.txt
  deploy/runtime/defaults/Fuel Cell_Single Owner.txt
  deploy/runtime/defaults/PV Battery_All Equity Partnership Flip.txt
  deploy/runtime/defaults/PV Battery_Commercial.txt
  deploy/runtime/defaults/PV Battery_Host Developer.txt
  deploy/runtime/defaults/PV Battery_Leveraged Partnership Flip.txt
  deploy/runtime/defaults/PV Battery_Merchant Plant.txt
  deploy/runtime/defaults/PV Battery_Residential.txt
  deploy/runtime/defaults/PV Battery_Sale Leaseback.txt
  deploy/runtime/defaults/PV Battery_Single Owner.txt
  deploy/runtime/defaults/PV Battery_Third Party.txt
  deploy/runtime/defaults/PVWatts Battery_Commercial.txt
  deploy/runtime/defaults/PVWatts Battery_Host Developer.txt
  deploy/runtime/defaults/PVWatts Battery_Residential.txt
  deploy/runtime/defaults/PVWatts Battery_Third Party.txt
  deploy/runtime/defaults/PVWatts_All Equity Partnership Flip.txt
  deploy/runtime/defaults/PVWatts_Commercial.txt
  deploy/runtime/defaults/PVWatts_Community Solar.txt
  deploy/runtime/defaults/PVWatts_Host Developer.txt
  deploy/runtime/defaults/PVWatts_LCOE Calculator.txt
  deploy/runtime/defaults/PVWatts_Leveraged Partnership Flip.txt
  deploy/runtime/defaults/PVWatts_Merchant Plant.txt
  deploy/runtime/defaults/PVWatts_None.txt
  deploy/runtime/defaults/PVWatts_Residential.txt
  deploy/runtime/defaults/PVWatts_Sale Leaseback.txt
  deploy/runtime/defaults/PVWatts_Single Owner.txt
  deploy/runtime/defaults/PVWatts_Third Party.txt
  deploy/runtime/ui/PV Land Area.txt
  deploy/runtime/ui/PV Shading.txt
  deploy/runtime/ui/PVWatts.txt
Labels: enhancement, requires help revision

#945 Remove crit_load input from PVWatts battery ReOpt calls
  src/invoke.cpp
Labels: bug
