Repository NREL/SAM, pull requests merged in 2022-05, with the labels that each got.

#1027 Fix Inverter Temp Derate table callback errors
  deploy/runtime/ui/Inverter Temp Derate CEC CG.txt
  deploy/runtime/ui/Inverter Temp Derate CEC DB.txt
  deploy/runtime/ui/Inverter Temp Derate DS.txt
  deploy/runtime/ui/Inverter Temp Derate PLC.txt
Labels: bug, pv

#1032 update vcut value for single owner and run export config
  api/api_autogen/library/defaults/Pvsamv1_PVBatterySingleOwner.json
  api/include/SAM_Pvsamv1.h
  api/modules/SAM_Pvsamv1.cpp
  deploy/runtime/defaults/PV Battery_Single Owner.txt
  deploy/runtime/ui/Battery Voltage.txt
Labels: bug

#1040 Update nameplate capacity for standalone battery systems
  deploy/runtime/defaults/Biopower_Merchant Plant.txt
  deploy/runtime/defaults/Biopower_Single Owner.txt
  deploy/runtime/defaults/DSLF_Merchant Plant.txt
  deploy/runtime/defaults/DSLF_Single Owner.txt
  deploy/runtime/defaults/ETES_Single Owner.txt
  deploy/runtime/defaults/Empirical Trough_Merchant Plant.txt
  deploy/runtime/defaults/Empirical Trough_Single Owner.txt
  deploy/runtime/defaults/Flat Plate PV_Merchant Plant.txt
  deploy/runtime/defaults/Flat Plate PV_Single Owner.txt
  deploy/runtime/defaults/Fuel Cell_Single Owner.txt
  deploy/runtime/defaults/Generic Battery_Merchant Plant.txt
  deploy/runtime/defaults/Generic Battery_Single Owner.txt
  deploy/runtime/defaults/Generic CSP System_Merchant Plant.txt
  deploy/runtime/defaults/Generic CSP System_Single Owner.txt
  deploy/runtime/defaults/Generic System_Merchant Plant.txt
  deploy/runtime/defaults/Generic System_Single Owner.txt
  deploy/runtime/defaults/Geothermal Power_Merchant Plant.txt
  deploy/runtime/defaults/Geothermal Power_Single Owner.txt
  deploy/runtime/defaults/High-X Concentrating PV_Merchant Plant.txt
  deploy/runtime/defaults/High-X Concentrating PV_Single Owner.txt
  deploy/runtime/defaults/MSLF_Merchant Plant.txt
  deploy/runtime/defaults/MSLF_Single Owner.txt
  deploy/runtime/defaults/MSPT_Merchant Plant.txt
  deploy/runtime/defaults/MSPT_Single Owner.txt
  deploy/runtime/defaults/PV Battery_Merchant Plant.txt
  deploy/runtime/defaults/PV Battery_Single Owner.txt
  deploy/runtime/defaults/PVWatts_Merchant Plant.txt
  deploy/runtime/defaults/PVWatts_Single Owner.txt
  deploy/runtime/defaults/Physical Trough_Merchant Plant.txt
  deploy/runtime/defaults/Physical Trough_Single Owner.txt
  deploy/runtime/defaults/Standalone Battery_Merchant Plant.txt
  deploy/runtime/defaults/Standalone Battery_Single Owner.txt
  deploy/runtime/defaults/Wind Power_Merchant Plant.txt
  deploy/runtime/defaults/Wind Power_Single Owner.txt
  deploy/runtime/ui/Financial Capacity Payments.txt
  deploy/runtime/ui/Financial Tax Credits.txt
  deploy/runtime/ui/Operating Costs Standalone Battery.txt
  test_results_win64.csv
Labels: bug, requires help revision

#1053 Button to copy inverter library data to user-specified
  deploy/runtime/ui/Inverter Datasheet.txt
Labels: requires help revision

#1059 Updated Windows defaults results based on ssc pull request 826
  test_results_win64.csv
Labels: bug, battery
