Repository NREL/SAM, pull requests merged in 2022-10, with the labels that each got.

#1169 Removed Land based BOS, Offshore BOS models from Res and Com Wind
  deploy/runtime/defaults/Wind Power_Commercial.json
  deploy/runtime/defaults/Wind Power_Residential.json
  deploy/runtime/startup.lk
  deploy/runtime/ui/Wind Farm Costs.txt
Labels: bug, wind

#1166 Land area calculations
  deploy/runtime/ui/PV Land Area.txt
  deploy/runtime/ui/PV Shading.txt
  deploy/runtime/ui/PVWatts.txt
Labels: bug, pv, requires help revision

#1171 UI warning for negative tilt angles
  deploy/runtime/ui/PV System Design.txt
Labels: bug, pv

#1182 Fix library folder writing in Advanced NSRDB downloads
  src/nsrdb.cpp
Labels: weather

#1191 Set enable rules to slope tilt, terrain
  deploy/runtime/ui/PV Shading.txt
  deploy/runtime/ui/PV System Design.txt
Labels: pv

#1198 Update test-results after reverting changes to POA irradiance reductions
  test_results_win64.csv
Labels: bug

#1199 Move spatial albedo heat maps to Spatial tab
  deploy/runtime/autographs.lk
  src/results.cpp
  src/results.h
  test_results_win64.csv
Labels: bug

#1164 Updated loss factor adjustments widget for lifetime, subhourly
  deploy/runtime/ui/Biopower Plant Specifications.txt
  deploy/runtime/ui/Dish Solar Field.txt
  deploy/runtime/ui/ETES System Control.txt
  deploy/runtime/ui/Empirical Trough Power Block.txt
  deploy/runtime/ui/Generic CSP Power Block.txt
  deploy/runtime/ui/Generic CSP Solar Field.txt
  deploy/runtime/ui/Generic System Plant.txt
  deploy/runtime/ui/Geothermal Plant and Equipment.txt
  deploy/runtime/ui/HCPV Array.txt
  deploy/runtime/ui/LF DSG System Design.txt
  deploy/runtime/ui/PBNS Power Block.txt
  deploy/runtime/ui/PV Losses.txt
  deploy/runtime/ui/PV2 Interconnection.txt
  deploy/runtime/ui/PVWatts Advanced Inputs.txt
  deploy/runtime/ui/Phys Trough System Control.txt
  deploy/runtime/ui/Physical Trough Power Block Common.txt
  deploy/runtime/ui/Physical Trough System Control.txt
  deploy/runtime/ui/Solar Water Heating.txt
  deploy/runtime/ui/Tower SolarPilot Solar Field.txt
  src/lossadj.cpp
  src/lossadj.h
  src/uiobjects.cpp
  src/widgets.cpp
Labels: new feature, requires help revision
