Repository NREL/SAM, pull requests merged in 2022-04, with the labels that each got.

#993 Generate wave resource JPD file from multiple years of time series data
  api/api_autogen/library/defaults/Lcoefcr_DSGLIPHLCOHCalculator.json
  api/api_autogen/library/defaults/LinearFresnelDsgIph_DSGLIPHLCOHCalculator.json
  api/api_autogen/library/defaults/LinearFresnelDsgIph_DSGLIPHNone.json
  api/include/SAM_CspDsgLfUi.h
  api/include/SAM_Equpartflip.h
  api/include/SAM_HostDeveloper.h
  api/include/SAM_IphToLcoefcr.h
  api/include/SAM_Levpartflip.h
  api/include/SAM_LinearFresnelDsgIph.h
  api/include/SAM_Saleleaseback.h
  api/include/SAM_Singleowner.h
  api/modules/SAM_CspDsgLfUi.cpp
  api/modules/SAM_LinearFresnelDsgIph.cpp
  deploy/runtime/ui/Marine Wave Resource Time Series.txt
  src/invoke.cpp
  src/library.cpp
  src/results.cpp
  src/wavetoolkit.cpp
  src/wavetoolkit.h
Labels: new feature

#1001 Fix Three Hour Data check in results.cpp
  src/results.cpp
Labels: bug

#1007 Custom htf
  deploy/runtime/ui/MSPT Receiver.txt
  deploy/runtime/ui/Physical Trough Solar Field.txt
Labels: bug

#1000 783 sequential wiring and transmission losses
  deploy/runtime/lossdiag.lk
Labels: bug, pv

#1023 update attributes for psm3-tmy to match the lk script
  src/nsrdb.cpp
Labels: bug
