Repository NREL/SAM, pull requests merged in 2022-11, with the labels that each got.

#1229 api changes caused by ssc 909 branch
  api/include/SAM_Battery.h
  api/include/SAM_EtesElectricResistance.h
  api/include/SAM_EtesPtes.h
  api/include/SAM_Pvsamv1.h
  api/include/SAM_Utilityrate5.h
  api/include/SAM_Utilityrateforecast.h
Labels: enhancement, utility rate

#1235 transition from strcpy to strncpy as appropriate
  api/api_autogen/export_config.cpp
  api/include/SAM_Battery.h
  api/include/SAM_Pvsamv1.h
  api/include/SAM_Utilityrate5.h
  api/include/SAM_Utilityrateforecast.h
  src/codegenerator.cpp
Labels: bug

#1222 Spatial UI page not showing correct help
  deploy/runtime/help/html/hmcontent.htm
  deploy/runtime/help/html/settings.js
  deploy/runtime/help/html/spatial.htm
  deploy/runtime/help/html/zoom_index.js
  deploy/runtime/help/html/zoom_pageinfo.js
  src/results.cpp
Labels: bug

#1241 Batt testing bugs
  deploy/runtime/defaults/MEwave Battery_Single Owner.json
  deploy/runtime/ui/Battery Bank Sizing.txt
  deploy/runtime/ui/Battery Current and Capacity.txt
  deploy/runtime/ui/Battery Enable.txt
  deploy/runtime/ui/Marine Costs - Battery O&M.txt
  deploy/runtime/ui/Marine Costs - Battery.txt
  deploy/runtime/ui/Marine Costs - O&M.txt
  deploy/runtime/ui/Marine Wave Resource Time Series.txt
  test_results_win64.csv
Labels: battery

#1253 Change spatial heat map labels
  src/results.cpp
  test_results_win64.csv
Labels: enhancement

#1255 Check for standalone battery before loading charging priority variables
  deploy/runtime/ui/Battery Dispatch Manual.txt
Labels: bug, battery

#1245 Atb defaults update script
  samples/ATB Defaults Update/README.md
  samples/ATB Defaults Update/atb_defaults_update.py
  samples/ATB Defaults Update/updaters.py
Labels: enhancement

#1266 Update wave download function to correctly handle cancel button press
  src/invoke.cpp
Labels: bug

#1270 Fixes to PV Capex cost curve tables
  deploy/runtime/ui/PV Capex Table AC.txt
  deploy/runtime/ui/PV Capex Table Battery.txt
  deploy/runtime/ui/PV Capex Table Land.txt
  deploy/runtime/ui/PV Capex Table.txt
Labels: bug, pv

#1272 Apply the fixes from #1270 to fuel cell table,…
  deploy/runtime/ui/PV Capex Fuel Cell.txt
  deploy/runtime/ui/PV Capex Table AC.txt
  deploy/runtime/ui/PV Capex Table Battery.txt
  deploy/runtime/ui/PV Capex Table Land.txt
  deploy/runtime/ui/PV Capex Table.txt
Labels: bug

#1275 allow battery replacement costs when the battery is disabled
  deploy/runtime/ui/Operating Costs Fuel Cell.txt
Labels: bug

#1282 Check whether bifacial electrical mismatch should be enabled on calculate option change
  deploy/runtime/ui/PV Losses.txt
Labels: bug, pv

#1286 Comment out logmsg as quick fix
  deploy/runtime/ui/Battery Dispatch Options BTM.txt
Labels: bug
