Repository NREL/SAM, pull requests merged in 2023-10, with the labels that each got.

#1489 Fix callbacks for wind bos system cost options for hybrids
  deploy/runtime/ui/Hybrid Costs.json
  deploy/runtime/ui/Wind Farm Costs.json
Labels: bug, dev bug

#1494 Remove duplicate sizing functions that were causing ac sizing issues
  deploy/runtime/ui/Battery Current and Capacity.json
Labels: bug, battery

#1492 Update Fuel Cell FOM dispatch options
  deploy/runtime/defaults/Fuel Cell_Single Owner.json
  deploy/runtime/defaults/Generic PVWatts Wind FuelCell Battery Hybrid_Single Owner.json
  deploy/runtime/defaults/PVWatts Wind FuelCell Battery Hybrid_Single Owner.json
  deploy/runtime/startup.lk
  deploy/runtime/ui/Fuel Cell Dispatch BTM.json
  deploy/runtime/ui/Fuel Cell Dispatch FOM.json
Labels: bug

#1495 rename price signals dispatch to retail rate
  deploy/runtime/startup.lk
  deploy/runtime/ui/Battery Dispatch Options BTM.json
  deploy/runtime/ui/Battery Dispatch Retail Rate.json
  deploy/runtime/ui/Battery Dispatch Standalone Options BTM.json
Labels: battery, requires help revision

#1501 Fix Send-to-Excel workbook to use cf_energy_sales instead of cf_energy_net
  deploy/runtime/cashflow.lk
  deploy/runtime/spreadsheets/community_solar.xlsx
  deploy/runtime/spreadsheets/host_developer.xlsx
  deploy/runtime/spreadsheets/merchant_plant.xlsx
  deploy/runtime/spreadsheets/partnership_flip.xlsx
  deploy/runtime/spreadsheets/single_owner.xlsx
Labels: bug

#1512 updated test results for peak shaving dispatch changes
  test_results_win64.csv
Labels: bug, battery

#1510 Tidal timeseries data
  deploy/runtime/defaults/MEtidal_LCOE Calculator.json
  deploy/runtime/defaults/MEtidal_None.json
  deploy/runtime/startup.lk
  deploy/runtime/ui/Marine Tidal Resource File.json
  deploy/runtime/ui/Marine Tidal Resource Header.json
  deploy/runtime/ui/Marine Tidal Resource.json
  deploy/tidal_resource/COD0911.csv
  deploy/tidal_resource/COI0303.csv
  deploy/tidal_resource/COI0501.csv
  deploy/tidal_resource/LIS1001.csv
  deploy/tidal_resource/NYH1924.csv
  deploy/tidal_resource/PEB0607.csv
  deploy/tidal_resource/PIR0705.csv
  deploy/tidal_resource/PUG1527.csv
  deploy/tidal_resource/PUG1624.csv
  deploy/tidal_resource/tidal_resource_testfile.csv
  src/invoke.cpp
  src/library.cpp
  src/library.h
  src/main.cpp
  src/wavetoolkit.cpp
  src/wavetoolkit.h
Labels: new feature

#1488 Disable default type for LCOE Calculator and No Financial
  deploy/runtime/ui/Geothermal Resource.json
Labels: bug
