Repository NREL/SAM, pull requests merged in 2023-11, with the labels that each got.

#1535 Fix configuration tree order
  deploy/runtime/startup.lk
Labels: dev bug

#1527 Sam 313 reopt v3 for resilience
  deploy/runtime/defaults/PV Battery_Commercial.json
  deploy/runtime/defaults/PV Battery_Host Developer.json
  deploy/runtime/defaults/PV Battery_Residential.json
  deploy/runtime/defaults/PV Battery_Third Party.json
  deploy/runtime/ui/Battery Model Simple with REopt.json
  deploy/runtime/ui/Battery REopt Optimization.json
  deploy/runtime/ui/Grid Outage.json
  deploy/runtime/webapis.conf
  src/invoke.cpp
Labels: bug, enhancement, battery, requires help revision

#1564 Add calcualtion for fuelcell cost per capacity, update defaults
  deploy/runtime/defaults/Generic PVWatts Wind FuelCell Battery Hybrid_Host Developer.json
  deploy/runtime/defaults/Generic PVWatts Wind FuelCell Battery Hybrid_Single Owner.json
  deploy/runtime/defaults/PVWatts Wind FuelCell Battery Hybrid_Host Developer.json
  deploy/runtime/defaults/PVWatts Wind FuelCell Battery Hybrid_Single Owner.json
  deploy/runtime/ui/Fuel Cell Costs Hybrid.json
Labels: dev bug

#1545 Update Residential / Commercial Cash Flow to Excel for Battery and Fuel Cell
  deploy/runtime/spreadsheets/residential_commercial.xlsx
Labels: bug

#1531 MSLF Capital Cost Total installed cost label bug
  deploy/runtime/ui/MSLF Capital Costs.json
  deploy/runtime/ui/MSLF IPH Capital Costs.json
Labels: csp
