Repository NREL/SAM, pull requests merged in 2024-12, with the labels that each got.

#1933 Add placeholder variables for IPH physical heat sink model
  deploy/runtime/defaults/MSLF IPH_Commercial.json
  deploy/runtime/defaults/MSLF IPH_LCOH Calculator.json
  deploy/runtime/defaults/MSLF IPH_None.json
  deploy/runtime/defaults/MSLF IPH_Single Owner.json
  deploy/runtime/defaults/MSPT IPH_LCOH Calculator.json
  deploy/runtime/defaults/MSPT IPH_None.json
  deploy/runtime/defaults/MSPT IPH_Single Owner.json
  deploy/runtime/defaults/Physical Trough IPH_Commercial.json
  deploy/runtime/defaults/Physical Trough IPH_LCOH Calculator.json
  deploy/runtime/defaults/Physical Trough IPH_None.json
  deploy/runtime/defaults/Physical Trough IPH_Single Owner.json
  deploy/runtime/ui/MSLF IPH System Design.json
  deploy/runtime/ui/MSPT IPH System Design.json
  deploy/runtime/ui/Physical Trough IPH System Design.json
Labels: csp

#1941 Fix iph trough model help links.
  deploy/runtime/startup.lk
Labels: csp, UI

#1962 Update version upgrade for CSP models.
  deploy/runtime/versions.lk
Labels: csp

#1943 Disable metering option from IPH commercial models.
  deploy/runtime/defaults/MSLF IPH_Commercial.json
  deploy/runtime/defaults/MSLF IPH_Single Owner.json
  deploy/runtime/defaults/Physical Trough IPH_Single Owner.json
  deploy/runtime/startup.lk
  deploy/runtime/ui/Utility Rate - Energy Charge.json
  deploy/runtime/ui/Utility Rate - Flat.json
Labels: csp, UI

#1958 Update default utility rates for hybrids and test script
  deploy/runtime/defaults/PVWatts Wind Battery Hybrid_Host Developer.json
  deploy/runtime/defaults/PVWatts Wind FuelCell Battery Hybrid_Host Developer.json
  deploy/runtime/defaults/Photovoltaic Wind Battery Hybrid_Host Developer.json
  test_results_win64.csv
Labels: dev bug

#1967 Update case comparison macro
  deploy/runtime/macros/Compare Cases.lk
  deploy/runtime/macros/Custom Generation Battery/Battery Compare Cases.lk
  deploy/runtime/macros/PV Battery/Battery Compare Cases.lk
  deploy/runtime/macros/Standalone Battery/Battery Compare Cases.lk
Labels: dev bug
