Repository NREL/SAM, pull requests merged in 2024-07, with the labels that each got.

#1812 Uncertainty defaults
  src/pvuncertainty.cpp
Labels: bug, pv

#1817 Fix tower HTF user properties bug
  deploy/runtime/ui/MSPT Receiver.json
Labels: added to release notes, csp, UI

#1823 Getem cost updates
  deploy/libraries/GETEMDefaults/Brownfield_Improved_EGS_Binary.json
  deploy/libraries/GETEMDefaults/Brownfield_Improved_EGS_Flash.json
  deploy/libraries/GETEMDefaults/Brownfield_Improved_Hydrothermal_Binary.json
  deploy/libraries/GETEMDefaults/Brownfield_Improved_Hydrothermal_Flash.json
  deploy/libraries/GETEMDefaults/Brownfield_Reference_EGS_Binary.json
  deploy/libraries/GETEMDefaults/Brownfield_Reference_EGS_Flash.json
  deploy/libraries/GETEMDefaults/Brownfield_Reference_Hydrothermal_Binary.json
  deploy/libraries/GETEMDefaults/Brownfield_Reference_Hydrothermal_Flash.json
  deploy/libraries/GETEMDefaults/Greenfield_Improved_EGS_Binary.json
  deploy/libraries/GETEMDefaults/Greenfield_Improved_EGS_Flash.json
  deploy/libraries/GETEMDefaults/Greenfield_Improved_Hydrothermal_Binary.json
  deploy/libraries/GETEMDefaults/Greenfield_Improved_Hydrothermal_Flash.json
  deploy/libraries/GETEMDefaults/Greenfield_Reference_EGS_Binary.json
  deploy/libraries/GETEMDefaults/Greenfield_Reference_EGS_Flash.json
  deploy/libraries/GETEMDefaults/Greenfield_Reference_Hydrothermal_Binary.json
  deploy/libraries/GETEMDefaults/Greenfield_Reference_Hydrothermal_Flash.json
  deploy/runtime/ui/Geothermal Costs.json
  deploy/runtime/ui/Geothermal Resource.json
  test_results_win64.csv
Labels: bug, geothermal

#1825 Uncertainty defaults fix
  src/pvuncertainty.cpp
Labels: bug, pv
