Repository NREL/SAM, pull requests merged in 2024-02, with the labels that each got.

#1696 Fix PV shading diagrams
  deploy/runtime/ui/PV Shading.json
  deploy/runtime/ui/PV Shading.png
  deploy/runtime/ui/PV Shading_object 12.png
  deploy/runtime/ui/PV Shading_self_shading_diagram.png
Labels: requires help revision, UI

#1692 Fix solar resource download geocoding issues
  deploy/runtime/ui/Solar Resource Data.json
  src/geotools.cpp
  src/invoke.cpp
  src/nsrdb.cpp
  src/nsrdb.h
Labels: requires help revision

#1698 Reset adjust periods to three zero columns when no custom period is set
  src/lossadj.cpp
Labels: bug, UI

#1697 Update PV land area calcs
  deploy/runtime/ui/PV Land Area.json
  deploy/runtime/ui/PV Shading.json
Labels: pv, requires help revision

#1694 Update array sizing for battery environment temperature
  deploy/runtime/ui/Battery Thermal.json
Labels: bug, battery

#1690 Add DC loss factor checks to PV, PV + battery report template
  deploy/runtime/reports/pv.samreport
  deploy/runtime/reports/pvbattery.samreport
Labels: pv

#1712 Fix PV time series shading
  deploy/runtime/ui/PV Shading.json
  deploy/runtime/ui/PVWatts Advanced Inputs.json
  src/invoke.cpp
  src/shadingfactors.cpp
Labels: UI

#1707 Fix fuel cell Dispatch page when opening older files
  deploy/runtime/versions.lk
Labels: UI

#1716 Fix URL to SAM forum from Help window
  src/main_add.h
Labels: UI

#1721 Fix #1682 PVWatts land area calculation
  deploy/runtime/ui/PV Land Area.json
Labels: bug

#1720 Add support for MSG V1.0.0 NSRDB API endpoint
  deploy/runtime/ui/Solar Resource Data.json
Labels: new feature

#1714 Improve REopt calls
  deploy/runtime/ui/Battery Model Simple with REopt.json
  deploy/runtime/ui/Battery REopt Optimization.json
  deploy/runtime/ui/Utility Rate - Billing Demand.json
  src/invoke.cpp
  src/simulation.cpp
Labels: bug, UI

#1709 Fix trough loop configuration label. Issue 1703
  deploy/runtime/ui/Physical Trough Collector Header.json
Labels: csp
