Repository NREL/SAM, pull requests merged in 2024-11, with the labels that each got.

#1897 Splash screen color for Fall 2024
  src/main_add.h
Labels: UI

#1894 Compare Cases macro
  deploy/runtime/macros/Compare Cases.lk
  deploy/runtime/macros/Custom Generation Battery/Battery Compare Cases.lk
  deploy/runtime/macros/PV Battery/Battery Compare Cases.lk
  deploy/runtime/macros/Standalone Battery/Battery Compare Cases.lk
Labels: enhancement, new feature

#1893 Update test results for NOCT model change
  test_results_win64.csv
Labels: pv, dev bug

#1916 Update version release date
  deploy/runtime/versions.lk
  src/main_add.h
Labels: architecture
