Repository NREL/SAM, pull requests merged in 2025-04, with the labels that each got.

#2051 Update splash color for SAM Spring 2025 release.
  src/main_add.h
Labels: UI

#2041 Retail rates grid export tests
  deploy/runtime/ui/Battery Dispatch Options BTM.json
Labels: enhancement, battery, requires help revision

#2053 Geocode zip to lat/lon for urdb utility rates
  deploy/runtime/webapis.conf
  src/urdb.cpp
Labels: utility rate, UI

#2049 Fix UI callback `crit_load` check for Custom Generation Battery configs
  deploy/runtime/reports/pvbattery.samreport
  deploy/runtime/ui/Electric Load Data.json
  deploy/runtime/ui/Utility Rate - Flat.json
Labels: bug, battery

#2056 Improve zip code error checks
  src/urdb.cpp
Labels: dev bug

#2066 Change inverter datasheet callbacks to allow for operation power consumption
  deploy/runtime/ui/Inverter Datasheet.json
Labels: pv
